GerenciarDespesas/Models/Salario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GerenciarDespesas.Models
{
    public class Salario
    {

        public int SalarioId { get; set; }

        public int MesId { get; set; }

        public Meses Meses { get; set; }
        [Required(ErrorMessage ="Campo Obrigatório.")]
        [Range(0, double.MaxValue,ErrorMessage =" Valor invalido.")]
        public double Valor { get; set; }
    }
}

GerenciarDespesas/Controllers/SalariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciarDespesas.Context;
using GerenciarDespesas.Models;

namespace GerenciarDespesas.Controllers
{
    public class SalariosController : Controller
    {
        private readonly Contexto _context;

        public SalariosController(Contexto context)
        {
            _context = context;
        }

        // GET: Salarios
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Salarios.Include(s => s.Meses).OrderBy(S => S.MesId);
            return View(await contexto.ToListAsync());
        }


        [HttpPost]
        public async Task<IActionResult> Index(string txtProcurar) // vou receber a informação do input
        {
            if (!String.IsNullOrEmpty(txtProcurar)) // se tiver alguma informação vou relalziar a consulta e trazer um lista
            {
                return View(await _context.Salarios.Include(s => s.Meses).Where(m => m.Meses.Nome.ToUpper().Contains(txtProcurar.ToUpper())).ToListAsync());

            }

            return View(await _context.Salarios.Include(s => s.Meses).OrderBy(S => S.MesId).ToListAsync()); // caso contrario trago todos 
        }




        // GET: Salarios/Create
        public IActionResult Create()
        {
            ViewData["MesId"] = new SelectList(_context.Meses, "MesId", "Nome");
            return View();
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SalarioId,MesId,Valor")] Salario salario)
        {
            if (ModelState.IsValid)
            {
                TempData["Confirmacao"] = "foi cadastrado com sucesso";
                _context.Add(salario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MesId"] = new SelectList(_context.Meses.Where(s => s.MesId != salario.MesId), "MesId", "Nome", salario.MesId);
            return View(salario);
        }

        // GET: Salarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salario = await _context.Salarios.FindAsync(id);
            if (salario == null)
            {
                return NotFound();
            }
            ViewData["MesId"] = new SelectList(_context.Meses.Where(s => s.MesId == salario.MesId), "MesId", "Nome", salario.MesId);
            return View(salario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SalarioId,MesId,Valor")] Salario salario)
        {
            if (id != salario.SalarioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(salario);
                    await _context.SaveChangesAsync();
                    TempData["Confirmacao"] = "foi atualizado com sucesso";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalarioExists(salario.SalarioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MesId"] = new SelectList(_context.Meses.Where(s => s.MesId != salario.MesId), "MesId", "Nome", salario.MesId);
            return View(salario);
        }

   


        [HttpPost]     
        public async Task<IActionResult> Delete(int id)
        {
            var salario = await _context.Salarios.FindAsync(id);
            _context.Salarios.Remove(salario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalarioExists(int id)
        {
            return _context.Salarios.Any(e => e.SalarioId == id);
        }
    }
}

GerenciarDespesas/Views/Salarios/Create.cshtml
@model GerenciarDespesas.Models.Salario

@{
    ViewData["Title"] = "Create";
}

<h1>Criar salario</h1>

<h4>Salario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MesId" class="control-label"></label>
                <select asp-for="MesId" class ="form-control" asp-items="ViewBag.MesId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciarDespesas/Views/Salarios/Edit.cshtml
@model GerenciarDespesas.Models.Salario

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Salario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SalarioId" />
            <div class="form-group">
                <label asp-for="MesId" class="control-label"></label>
                <select asp-for="MesId" class="form-control" asp-items="ViewBag.MesId"></select>
                <span asp-validation-for="MesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciarDespesas/Views/Salarios/Index.cshtml
@model IEnumerable<GerenciarDespesas.Models.Salario>

@{
    ViewData["Title"] = "Index";
}

<h1>Salarios Cadastrados</h1>

<div class="table">

    <div class="container">


        <p class="btnNovo">
            <a asp-action="Create" class="btn btn-outline-primary btn-sm">Novo</a>
        </p>


        @if (TempData["Confirmacao"] != null)
        {
            <h6 class="alert alert-sucess"> @TempData["Confirmacao"]</h6>
        }

        <form asp-action="Index" asp-controller="Salarios" method="post">
            @*  campo de pesquisar *@

            <div class="form-group">
                <div class="input-group col-md-6">
                    <input class="form-control" name="txtProcurar" />  @*String que devo informar na control*@
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-dark"> <i class="fas fa-search-plus"></i></button>
                    </div>
                </div>
            </div>
        </form>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Meses)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Valor)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Meses.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Valor)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.SalarioId" class="btn btn-outline-info btn-sm">Atualizar</a> |

                            <a class="btn btn-outline-danger btn-sm" onclick="ExibirModal(@item.SalarioId)">Excluir</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Deseja prosseguir com a exclusão do salario.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btnExcluir">Sim</button>
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Não</button>

            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script>
        function ExibirModal(id) {

          
            $(".modal").modal();

            $(".btnExcluir").on('click', function () {
                $.ajax({
                    url: "Salarios/Delete",
                    method: "POST",
                    data: { id: id },
                    success: function (data) {
                        $(".modal").modal('hide');
                        location.reload(true);
                    }


                });
            });
        }
    </script>
} 